### ISSUE TITLE
touchpad and sound dosent work

### ISSUE THREAD

**Issue by theMonk3y** [adrianjagielak/lenovo_y530_efi#1]
Hey adrian! thank you for sharing!
i try this EFI on my y530 15inch i7 (8th Gen).
Touchpad dosent work i think its problem from config. 
Sound dosent works to.

**Comment by adrianjagielak** [comment]
Hi! Sorry for the late reply and thank you for your interest in my EFI!
Unfortunately, I do not own y530 (only [Y520](https://github.com/adrianjagielak/lenovo_y520_efi)) and this repo contains EFI of some other person that I tweaked for him just to boot and I thought I share it. I will ping him, he probably solved it already

**Comment by theMonk3y** [comment]
hi dude! ok thank you!!

**Comment by adrianjagielak** [comment]
Unfortunately, he never solved touchpad and sound, you are on your own :( But if you ever find a solution feel free to send it to me and I will add it to this repo :)

**Comment by theMonk3y** [comment]
Hey dude! checki this [repo](https://github.com/chilledHamza/Hackintosh_Legion_Y7000_2018), this EFI works pretty good on Big Sur! take some ideas and help the community! xD

@chilledHamza

**Comment by adrianjagielak** [comment]
Thanks! I will merge this into my repo if I will have free time soon:)
